import type {Metadata} from "next";
import {NextUIProvider} from '@nextui-org/react'
import "../styles/globals.css";

export const metadata: Metadata = {
    title: "Lottery",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`antialiased`}
        >
        <NextUIProvider>
            {children}
        </NextUIProvider>
        </body>
        </html>
    );
}
