import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarApp from "@/components/NavbarApp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex w-full h-screen ">
          <div className="flex items-center justify-center h-screen w-1/3">
          </div>
          <div className="flex flex-col h-screen w-1/3 relative bg-gradient-to-b to-blue-500/20 from-blue-500/5 ">
            <NavbarApp />
            <div className="">
              {children}
            </div>
          </div>
          <div className="flex items-center justify-center h-screen w-1/3">
          </div>
        </div>
      </body>
    </html>
  );
}
