import type { Metadata } from "next";
import NavbarApp from "@/components/NavbarApp";
import { NextUIProvider } from '@nextui-org/react'
import "../styles/globals.css";

export const metadata: Metadata = {
    title: "Lottery",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`antialiased`}
            >
                <NextUIProvider>
                    <div className="flex w-full h-screen ">
                        <div className="flex items-center justify-center h-screen w-1/3">
                        </div>
                        <div className="flex flex-col h-screen w-1/3 relative bg-gradient-to-b to-blue-500/20 from-blue-500/5 ">
                            <NavbarApp />
                            <div className="">
                                {children}
                            </div>
                        </div>
                        <div className="flex items-center justify-center h-screen w-1/3">
                        </div>
                    </div>
                </NextUIProvider>
            </body>
        </html>
    );
}
