import type { Metadata } from "next";
// import "../styles/globals.css";

export const metadata: Metadata = {
   title: "Lottery Settings",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <div>
         {children}
      </div>
   );
}
